import type { Metadata } from "next";

import Navbar from "@/components/shared/Gennextfooter";
// import Navigation from "@/components/pages/Navbar";
import CombinedLayout from "@/components/NavigationWithoutDashboard";
import { Toaster } from "@/components/ui/toaster";
// import Footer from "@/components/shared/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
    
          <CombinedLayout />
            {children}
            <Toaster/>
          {/* <Navbar /> */}
        
      </body>
    </html>
  );
}
